-- 코드를 입력하세요
SELECT
    p.PRODUCT_CODE,
    SUM(s.SALES_AMOUNT) * p.PRICE AS SALES
FROM OFFLINE_SALE s
JOIN PRODUCT p
  ON s.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    p.PRODUCT_CODE,
    p.PRICE
ORDER BY
    SALES DESC,
    p.PRODUCT_CODE ASC;