-- 코드를 입력하세요
SELECT p.PRODUCT_CODE,
       SUM(s.SALES_AMOUNT) * p.PRICE AS SALES
FROM OFFLINE_SALE s JOIN PRODUCT p 
ON s.PRODUCT_ID = p.PRODUCT_ID
GROUP BY s.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC